# Main Costa makefile
# By Jacob Palm
# Licensed under the MIT License. See LICENSE file for details.
#
# Ensure "make" utility is available in your PATH before running.
# Built and tested with Borland Make 3.6
#
# To build all units and applications, run:
#   make all
#
# To build all library units, run:
#   make library
#
# To build only specific applications, run:
#   make COSTA.EXE
#   make DESKTOP.EXE
#   etc.
#
# To build package for SvarDOS, run:
#   make SVARDOS

# Paths for Costa and its source files
COSTADIR   = C:\COSTA
LIBDIR     = $(COSTADIR)\LIBRARY
SOURCEDIR  = $(COSTADIR)\SOURCE

# Output path for SvarDOS build
SVARDIR    = $(COSTADIR)\SVARDOS
SVARAPPDIR = $(SVARDIR)\PROGS\COSTA

# Paths for compilers/linkers - recommended to add these in your PATH, but can be set here
TPC = TPC
TASM = TASM
TLINK = TLINK
BINOBJ = BINOBJ

# Zip command for SvarDOS packaging - using Info-ZIP
ZIPCMD = ZIP -9rkDX

# Settings for compilers/linkers

# -M   = Make modified units
# -$D- = Disable debug info
# -$L- = Disable local debug symbols
# -$R- = Disable range checking and virtual method call checking
# -GD  = Generate detailed map file for each executable
TPCSWITCHES = -M -GD -$D-
TPCCMD = $(TPC) $(TPCSWITCHES)

# TASM/TLINK options for COSTA.EXE
# /ZN = Debug info disabled
TASMSWITCHES = /zi /v
TASMCMD = $(TASM) $(TASMSWITCHES)
# /m = MAP
# /t = Make COM program
TLINKSWITCHES = /t
TLINKCMD = $(TLINK) $(TLINKSWITCHES)

# BINOBJ options for building binary object files, used for graphics drivers
BINOBJCMD = $(BINOBJ)

# Compiler paths for library and application source files
LIBPATHS = -U$(LIBDIR) -I$(LIBDIR) -O$(LIBDIR) -E$(COSTADIR)
APPPATHS = -U$(SOURCEDIR) -I$(SOURCEDIR) -O$(SOURCEDIR) -E$(COSTADIR)

# Generate all applications #################################################

ALL: COSTA.COM DESKTOP.EXE ICONEDIT.EXE MINES.EXE TEXTVIEW.EXE CONFIG.EXE CALC.EXE TICTAC.EXE THMEDIT.EXE
	@echo.
	@echo All applications built.

# Launcher ##################################################################

COSTA.COM: COSTA.OBJ
	$(TLINKCMD) COSTA.OBJ

COSTA.OBJ: $(SOURCEDIR)\COSTA.ASM
	$(TASMCMD) $(SOURCEDIR)\COSTA.ASM

# Desktop ###################################################################

DESKTOP.EXE: $(SOURCEDIR)\DESKTOP.PAS LIBRARY
	$(TPCCMD) $(SOURCEDIR)\DESKTOP.PAS $(APPPATHS)

# Desktop Edit Link dialog
DESKEDIT.TPU: $(SOURCEDIR)\DESKEDIT.PAS LIBRARY
	$(TPCCMD) $(SOURCEDIR)\DESKEDIT.PAS $(APPPATHS)

# Desktop link menu
DESKMENU.TPU: $(SOURCEDIR)\DESKMENU.PAS LIBRARY
	$(TPCCMD) $(SOURCEDIR)\DESKMENU.PAS $(APPPATHS)

# Desktop icon area
UIDESK.TPU: $(LIBDIR)\UIDESK.PAS LIBRARY
	$(TPCCMD) $(LIBDIR)\UIDESK.PAS $(LIBPATHS)

# Icon Editor ###############################################################

ICONEDIT.EXE: $(SOURCEDIR)\ICONEDIT.PAS LIBRARY UIICONCV.TPU
	$(TPCCMD) $(SOURCEDIR)\ICONEDIT.PAS $(APPPATHS)

# Icon canvas
UIICONCV.TPU: $(LIBDIR)\UIICONCV.PAS LIBRARY
	$(TPCCMD) $(LIBDIR)\UIICONCV.PAS $(LIBPATHS)

# Minesweeper ###############################################################

MINES.EXE: $(SOURCEDIR)\MINES.PAS LIBRARY UIMINEFL.TPU
	$(TPCCMD) $(SOURCEDIR)\MINES.PAS $(APPPATHS)

# Minefield UI control
UIMINEFL.TPU: $(LIBDIR)\UIMINEFL.PAS COSTALIB.TPU
	$(TPCCMD) $(LIBDIR)\UIMINEFL.PAS $(LIBPATHS)

# Text Viewer ###############################################################

TEXTVIEW.EXE: $(SOURCEDIR)\TEXTVIEW.PAS LIBRARY
	$(TPCCMD) $(SOURCEDIR)\TEXTVIEW.PAS $(APPPATHS)

# Theme Editor ##############################################################

THMEDIT.EXE: $(SOURCEDIR)\THMEDIT.PAS LIBRARY
   $(TPCCMD) $(SOURCEDIR)\THMEDIT.PAS $(APPPATHS)

# Calculator ################################################################

CALC.EXE: $(SOURCEDIR)\CALC.PAS LIBRARY
   $(TPCCMD) $(SOURCEDIR)\CALC.PAS $(APPPATHS)

# Tic Tac Toe ###############################################################

TICTAC.EXE: $(SOURCEDIR)\TICTAC.PAS LIBRARY
   $(TPCCMD) $(SOURCEDIR)\TICTAC.PAS $(APPPATHS)

# Configuration Utility #####################################################

CONFIG.EXE: $(SOURCEDIR)\CONFIG.PAS LIBRARY
	$(TPCCMD) $(SOURCEDIR)\CONFIG.PAS $(APPPATHS)

# Library ###################################################################

# All library units
LIBRARY: COSTALIB.TPU UIAREA.TPU UIBUTTON.TPU UICHKBOX.TPU UIFRAME.TPU UIICON.TPU UILABEL.TPU UILIST.TPU UITIMER.TPU UITXTBOX.TPU UILOG.TPU UITHMPRW.TPU ABOUTDLG.TPU FILEDLG.TPU INPUTDLG.TPU MSGDLG.TPU RUNDLG.TPU

# Main library
COSTALIB.TPU: $(LIBDIR)\COSTALIB.PAS
	$(TPCCMD) $(LIBDIR)\COSTALIB.PAS $(LIBPATHS)

# UI Objects
UIAREA.TPU: $(LIBDIR)\UIAREA.PAS COSTALIB.TPU
	$(TPCCMD) $(LIBDIR)\UIAREA.PAS $(LIBPATHS)

UIBUTTON.TPU: $(LIBDIR)\UIBUTTON.PAS COSTALIB.TPU
	$(TPCCMD) $(LIBDIR)\UIBUTTON.PAS $(LIBPATHS)

UICHKBOX.TPU: $(LIBDIR)\UICHKBOX.PAS COSTALIB.TPU
	$(TPCCMD) $(LIBDIR)\UICHKBOX.PAS $(LIBPATHS)

UIFRAME.TPU: $(LIBDIR)\UIFRAME.PAS COSTALIB.TPU
	$(TPCCMD) $(LIBDIR)\UIFRAME.PAS $(LIBPATHS)

UIICON.TPU: $(LIBDIR)\UIICON.PAS COSTALIB.TPU
	$(TPCCMD) $(LIBDIR)\UIICON.PAS $(LIBPATHS)

UILABEL.TPU: $(LIBDIR)\UILABEL.PAS COSTALIB.TPU
	$(TPCCMD) $(LIBDIR)\UILABEL.PAS $(LIBPATHS)

UILIST.TPU: $(LIBDIR)\UILIST.PAS COSTALIB.TPU UIAREA.TPU
	$(TPCCMD) $(LIBDIR)\UILIST.PAS $(LIBPATHS)

UITIMER.TPU: $(LIBDIR)\UITIMER.PAS COSTALIB.TPU
	$(TPCCMD) $(LIBDIR)\UITIMER.PAS $(LIBPATHS)

UILOG.TPU: $(LIBDIR)\UILOG.PAS COSTALIB.TPU UIAREA.TPU
	$(TPCCMD) $(LIBDIR)\UILOG.PAS $(LIBPATHS)

UITXTBOX.TPU: $(LIBDIR)\UITXTBOX.PAS COSTALIB.TPU UIAREA.TPU
	$(TPCCMD) $(LIBDIR)\UITXTBOX.PAS $(LIBPATHS)

UITHMPRW.TPU: $(LIBDIR)\UITHMPRW.PAS LIBRARY
	$(TPCCMD) $(LIBDIR)\UITHMPRW.PAS $(LIBPATHS)

# Dialogs
ABOUTDLG.TPU: $(LIBDIR)\ABOUTDLG.PAS
	$(TPCCMD) $(LIBDIR)\ABOUTDLG.PAS $(LIBPATHS)

FILEDLG.TPU: $(LIBDIR)\FILEDLG.PAS
	$(TPCCMD) $(LIBDIR)\FILEDLG.PAS $(LIBPATHS)

INPUTDLG.TPU: $(LIBDIR)\INPUTDLG.PAS
	$(TPCCMD) $(LIBDIR)\INPUTDLG.PAS $(LIBPATHS)

MSGDLG.TPU: $(LIBDIR)\MSGDLG.PAS
	$(TPCCMD) $(LIBDIR)\MSGDLG.PAS $(LIBPATHS)

RUNDLG.TPU: $(LIBDIR)\RUNDLG.PAS
	$(TPCCMD) $(LIBDIR)\RUNDLG.PAS $(LIBPATHS)


# SvarDOS build #############################################################

SVARDOS: ALL
	DELTREE /Y $(SVARDIR)\PROGS
	MKDIR $(SVARDIR)\PROGS
	MKDIR $(SVARDIR)\PROGS\COSTA
	MKDIR $(SVARDIR)\PROGS\COSTA\CONFIG
	MKDIR $(SVARDIR)\PROGS\COSTA\ICONS
	MKDIR $(SVARDIR)\PROGS\COSTA\THEMES
	COPY $(COSTADIR)\*.EXE $(SVARAPPDIR) /Y
	COPY $(COSTADIR)\*.TXT $(SVARAPPDIR) /Y
	COPY $(COSTADIR)\LICENSE $(SVARAPPDIR)/Y
	XCOPY $(COSTADIR)\CONFIG $(SVARAPPDIR)\CONFIG /Y
	XCOPY $(COSTADIR)\ICONS $(SVARAPPDIR)\ICONS /Y
	XCOPY $(COSTADIR)\THEMES $(SVARAPPDIR)\THEMES /Y

	# Delete user config files, to provide fresh defaults
	DEL $(SVARAPPDIR)\CONFIG\DESK?.BIN

	# Delete MacOS junk files, if any
	DEL $(SVARDIR)\DS_STO~1
	DEL $(SVARDIR)\APPINFO\DS_STO~1
	DEL $(SVARDIR)\PROGS\DS_STO~1
	DEL $(SVARAPPDIR)\DS_STO~1
	DEL $(SVARAPPDIR)\CONFIG\DS_STO~1
	DEL $(SVARAPPDIR)\ICONS\DS_STO~1
	DEL $(SVARAPPDIR)\THEMES\DS_STO~1

	# Development files start with underscore, delete them
	DEL $(SVARAPPDIR)\_*.*

	# Create zip package - SVP extension required by SvarDOS
	CD $(SVARDIR)
	$(ZIPCMD) COSTA.SVP . | MORE
	MOVE COSTA.SVP $(COSTADIR) /Y
	CD $(COSTADIR)

# Clean up ##################################################################

CLEAN:
	del $(COSTADIR)\*.TPU
	del $(COSTADIR)\*.OBJ
	del $(COSTADIR)\*.MAP
	@echo.
	@echo Cleaned up build files.
